#控制击杀信息提示发送玩家范围（默认：true）
只给相同世界的玩家发送信息: true
#启用stattrack需要的经济数量（默认：1000）
击杀记录: 1000
#在该段时间内连续击杀会进行连杀提示（单位：秒、默认：30）
连杀间隔: 30
#武器lore击杀记录文本（默认：已击杀）
lore文本: 已击杀
#武器击杀数增加提示信息(支持使用"&"替代"§")
击杀数增加提示: §d[%weapon%§d] §1已击杀-%amount%
#击杀提示，支持多行随机(击杀者：%killer%、被击杀者：%player%、使用的武器：%weapon%)
击杀提示信息:
  - §a%killer% §r[%weapon%§r] §c%player%
  - §a%killer% §r使用 %weapon% §r抹除了 §c%player%