name: DESOLATE_KillInformation
version: '1.0-SNAPSHOT'
main: top.mores.KillInformation
api-version: '1.18'
authors: [ Mores ]
description: 击杀信息
commands:
  kf:
    description: KillInformation Command
    usage: /kf <reload>[<cx>] {<PlayerName>}
    permission: op